# Generated by Django 2.2.2 on 2019-07-06 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adresse', '0001_initial'),
        ('orders', '0004_auto_20190705_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_adress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_adress', to='adresse.Address'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_adress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_adress', to='adresse.Address'),
        ),
    ]
