# Generated by Django 2.2.2 on 2019-07-07 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20190706_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_adress',
        ),
    ]
