# Generated by Django 2.2.2 on 2019-06-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-time',)},
        ),
        migrations.AddField(
            model_name='product',
            name='view',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
