# Generated by Django 2.2.2 on 2019-07-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='s_totla',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
