# Generated by Django 2.2.2 on 2019-07-06 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(blank=True, choices=[('billing', 'Billing'), ('shipping', 'shipping')], max_length=120, null=True)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('country', models.CharField(choices=[('bangladesh', 'Bangladesh'), ('india', 'India'), ('america', 'America'), ('nepal', 'Nepal'), ('japan', 'Japan'), ('algeria', 'Algeria')], default='bangladesh', max_length=120)),
                ('adress_1', models.CharField(max_length=120)),
                ('adress_2', models.CharField(blank=True, max_length=120, null=True)),
                ('country_state', models.CharField(max_length=120)),
                ('post_or_zip', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=120)),
                ('billing_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.BillingProfile')),
            ],
        ),
    ]
