# Generated by Django 2.2.2 on 2019-07-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adresse', '0002_auto_20190707_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(blank=True, choices=[('shipping', 'Shipping')], max_length=120, null=True),
        ),
    ]
