# Generated by Django 2.2.2 on 2019-07-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adresse', '0003_auto_20190707_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='prescription',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
